// @generated by protoc-gen-connect-web v0.8.1 with parameter "target=ts"
// @generated from file rpc/interview/interview_service.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  DataStreamRequest,
  DataStreamResponse,
  HelloRequest,
  HelloResponse,
} from "./interview_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service InterviewService
 */
export const InterviewService = {
  typeName: "InterviewService",
  methods: {
    /**
     * Say hello, and get a response
     *
     * @generated from rpc InterviewService.Hello
     */
    hello: {
      name: "Hello",
      I: HelloRequest,
      O: HelloResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Initiate a stream of data messages from the server
     *
     * @generated from rpc InterviewService.DataStream
     */
    dataStream: {
      name: "DataStream",
      I: DataStreamRequest,
      O: DataStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  },
} as const;
